version: "3.2"

services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd!
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi_user
      MYSQL_PASSWORD: glpi
    expose:
      - "3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    restart: always

  
  glpi:
    build: glpi
    ports:
      - "8080:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - mysql
